---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "ServiceAccount"
  metadata:
    labels:
      provider: "fabric8"
      project: "exposecontroller"
      version: "2.2.297"
      group: "io.fabric8.devops.apps"
    name: "exposecontroller"
- apiVersion: "v1"
  kind: "ConfigMap"
  metadata:
    labels:
      provider: "fabric8"
      project: "exposecontroller"
      version: "2.2.297"
      group: "io.fabric8.devops.apps"
    name: "exposecontroller"
  data:
    config.yml: "domain:\nexposer:\n"
- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    annotations:
      configmap.fabric8.io/update-on-change: "exposecontroller"
      fabric8.io/git-commit: "0958d61020835b9707536cc0525344fc30a764dd"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=exposecontroller&var-version=2.2.297"
      fabric8.io/build-id: "4"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/4"
      fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/exposecontroller/src/main/fabric8/icon.png"
      fabric8.io/git-branch: "release-v2.2.297"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/0958d61020835b9707536cc0525344fc30a764dd"
    labels:
      provider: "fabric8"
      project: "exposecontroller"
      version: "2.2.297"
      group: "io.fabric8.devops.apps"
    name: "exposecontroller"
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: "exposecontroller"
        provider: "fabric8"
        group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: "0958d61020835b9707536cc0525344fc30a764dd"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=exposecontroller&var-version=2.2.297"
          fabric8.io/build-id: "4"
          fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/4"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/exposecontroller/src/main/fabric8/icon.png"
          configmap.fabric8.io/update-on-change: "exposecontroller"
          fabric8.io/git-branch: "release-v2.2.297"
          fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/0958d61020835b9707536cc0525344fc30a764dd"
        labels:
          provider: "fabric8"
          project: "exposecontroller"
          version: "2.2.297"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/exposecontroller:2.2.297"
          name: "exposecontroller"
          volumeMounts:
          - mountPath: "/etc/exposecontroller"
            name: "config-volume"
        serviceAccountName: "exposecontroller"
        volumes:
        - configMap:
            name: "exposecontroller"
          name: "config-volume"
