---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "ConfigMap"
  metadata:
    labels:
      provider: "fabric8"
      project: "ingress-nginx"
      version: "2.2.297"
      group: "io.fabric8.devops.apps"
    name: "nginx-config"
    namespace: "fabric8-system"
  data:
    client-max-body-size: "2000m"
    proxy-connect-timeout: "500s"
    proxy-read-timeout: "500s"
    server-names-hash-bucket-size: "256"
    server-names-hash-max-size: "1024"
- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    annotations:
      configmap.fabric8.io/update-on-change: "nginx-config"
      fabric8.io/git-commit: "0958d61020835b9707536cc0525344fc30a764dd"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=ingress-nginx&var-version=2.2.297"
      fabric8.io/build-id: "4"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/4"
      fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/ingress-nginx/src/main/fabric8/icon.png"
      fabric8.io/git-branch: "release-v2.2.297"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/0958d61020835b9707536cc0525344fc30a764dd"
    labels:
      provider: "fabric8"
      project: "ingress-nginx"
      version: "2.2.297"
      group: "io.fabric8.devops.apps"
    name: "ingress-nginx"
    namespace: "fabric8-system"
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: "ingress-nginx"
        provider: "fabric8"
        group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: "0958d61020835b9707536cc0525344fc30a764dd"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=ingress-nginx&var-version=2.2.297"
          fabric8.io/build-id: "4"
          fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/4"
          fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/ingress-nginx/src/main/fabric8/icon.png"
          configmap.fabric8.io/update-on-change: "nginx-config"
          fabric8.io/git-branch: "release-v2.2.297"
          fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/0958d61020835b9707536cc0525344fc30a764dd"
        labels:
          provider: "fabric8"
          project: "ingress-nginx"
          version: "2.2.297"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args:
          - "-v=3"
          - "-nginx-configmaps=fabric8-system/nginx-config"
          image: "nginxdemos/nginx-ingress:0.3.1"
          name: "nginx-ingress"
          ports:
          - containerPort: 80
            hostPort: 80
            name: "http"
            protocol: "TCP"
          - containerPort: 443
            hostPort: 443
            name: "https"
            protocol: "TCP"
        nodeSelector:
          fabric8.io/externalIP: "true"
